# file: tests/bash/lab.sh
# use: source ./tests/bash/lab.sh   (every new terminal, or after editing .env / .env.bash)
# requires: bash, curl, jq, python3, openssl, docker compose
# All JSON is built with jq so quoting/UTF-8 stays correct.

export PYTHONUTF8=1

# repo root = two levels up from this file (tests/bash/lab.sh)
LAB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAB_ROOT="$(cd "$LAB_DIR/../.." && pwd)"
export LAB_DIR LAB_ROOT

# ---------------------------------------------------------------- env loading
# replaces: set -a; source .env; set +a
import_dotenv() { # $1 = path (default $LAB_ROOT/.env)
  local path="${1:-$LAB_ROOT/.env}" line name value
  [ -f "$path" ] || return 0
  while IFS= read -r line || [ -n "$line" ]; do
    [[ $line =~ ^[[:space:]]*(export[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=(.*)$ ]] || continue
    name="${BASH_REMATCH[2]}"
    value="${BASH_REMATCH[3]}"
    case "$value" in
      \"*\"|\'*\') ;;                       # quoted: keep as is, a # inside is part of the value
      *) value="${value%%[[:space:]]#*}" ;; # otherwise drop a trailing " # comment"
    esac
    value="$(printf '%s' "$value" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
    case "$value" in                        # unwrap one layer of quotes, like docker compose env_file
      \"*\") value="${value#\"}"; value="${value%\"}" ;;
      \'*\') value="${value#\'}"; value="${value%\'}" ;;
    esac
    export "$name=$value"
  done < "$path"
}

# .env.bash (generated by tests/bash/env2bash.sh) is preferred: it is plain bash.
# Falls back to parsing .env directly.
load_env() {
  if [ -f "$LAB_ROOT/.env.bash" ]; then
    # shellcheck disable=SC1091
    source "$LAB_ROOT/.env.bash"
  else
    import_dotenv "$LAB_ROOT/.env"
  fi
}
load_env

# write/replace NAME=VALUE in .env (and in .env.bash when it exists) and in the current shell
set_dotenv() { # $1 = name, $2 = value, $3 = path (default $LAB_ROOT/.env)
  local name="$1" value="$2" path="${3:-$LAB_ROOT/.env}" tmp bashfile
  [ -f "$path" ] || : > "$path"
  tmp="$(mktemp)"
  grep -v -E "^(export[[:space:]]+)?${name}=" "$path" > "$tmp" || true
  printf '%s=%s\n' "$name" "$value" >> "$tmp"
  tr -d '\r' < "$tmp" > "$path"
  rm -f "$tmp"
  bashfile="$LAB_ROOT/.env.bash"
  if [ -f "$bashfile" ] && [ "$path" = "$LAB_ROOT/.env" ]; then
    tmp="$(mktemp)"
    grep -v -E "^(export[[:space:]]+)?${name}=" "$bashfile" > "$tmp" || true
    printf 'export %s=%s\n' "$name" "$(printf '%s' "$value" | sed "s/'/'\\\\''/g; s/^/'/; s/\$/'/")" >> "$tmp"
    tr -d '\r' < "$tmp" > "$bashfile"
    rm -f "$tmp"
  fi
  export "$name=$value"
}

# ------------------------------------------------------------- hosts / ports
# Every URL below comes from LAB_HOST. Override any of these in .env.bash
# (or in the shell before sourcing this file) to point the tests at another machine.
LAB_HOST="${LAB_HOST:-localhost}"
LITELLM_PORT="${LITELLM_PORT:-4000}"
IDP_PORT="${IDP_PORT:-8080}"
BILLING_PORT="${BILLING_PORT:-8090}"
GATEWAY_PORT="${GATEWAY_PORT:-80}"

LAB="${LAB:-http://${LITELLM_HOST:-$LAB_HOST}:$LITELLM_PORT}"          # litellm-proxy, direct
IDP_URL="${IDP_URL:-http://${IDP_HOST:-$LAB_HOST}:$IDP_PORT}"          # keycloak
IDP_REALM="${IDP_REALM:-lab}"
BILLING_URL="${BILLING_URL:-http://${BILLING_HOST:-$LAB_HOST}:$BILLING_PORT}"  # subscription-service

# edge-gateway (caddy) routes by Host name, so these stay names, not IPs.
# To reach a remote gateway keep the names and add, in .env.bash:
#   LAB_CURL_OPTS="--resolve api.localhost:80:<ip> --resolve llm.localhost:80:<ip>"
API_HOST="${API_HOST:-api.localhost}"
LLM_HOST="${LLM_HOST:-llm.localhost}"
_port_suffix() { [ "$GATEWAY_PORT" = 80 ] && printf '' || printf ':%s' "$GATEWAY_PORT"; }
API_URL="${API_URL:-http://${API_HOST}$(_port_suffix)}"
LLM_URL="${LLM_URL:-http://${LLM_HOST}$(_port_suffix)}"
LAB_CURL_OPTS="${LAB_CURL_OPTS:-}"           # extra curl options, e.g. --resolve ...
JSON='application/json; charset=utf-8'

export LAB_HOST LITELLM_PORT IDP_PORT BILLING_PORT GATEWAY_PORT
export LAB IDP_URL IDP_REALM BILLING_URL API_HOST LLM_HOST API_URL LLM_URL LAB_CURL_OPTS JSON

# ------------------------------------------------------------------ helpers
# replaces openssl rand -hex N (same thing here, kept for parity with lab.ps1)
new_rand_hex() { openssl rand -hex "$1"; }

# write a file as UTF-8 without BOM and LF only
write_lf() { # $1 = path, $2 = text
  printf '%s' "$2" | tr -d '\r' > "$1"
}

# curl with the lab-wide options applied (LAB_CURL_OPTS is intentionally unquoted)
lab_curl() { curl $LAB_CURL_OPTS "$@"; }

# POST JSON to LiteLLM (master key by default) -> prints the raw response body
invoke_lab() { # $1 = path, $2 = json body, $3 = key (default master key)
  local p="$1" body="$2" key="${3:-$LITELLM_MASTER_KEY}"
  lab_curl -sS -X POST "$LAB$p" \
    -H "Authorization: Bearer $key" -H "Content-Type: $JSON" -d "$body"
}

# only the HTTP status code (= curl -s -o /dev/null -w "%{http_code}")
# usage: http_code URL [any extra curl args: -X POST -H ... -d ...]
http_code() {
  local err code
  err="$(mktemp)"
  if code="$(lab_curl -sS -o /dev/null -w '%{http_code}' "$@" 2>"$err")"; then
    printf '%s' "$code"
  else
    printf 'ERR: %s' "$(tr '\n' ' ' < "$err" | sed -E 's/[[:space:]]+$//')"
  fi
  rm -f "$err"
}

# = code() in the original: status code of a chat completion through litellm-proxy
test_chat_code() { # $1 = key, $2 = model, $3 = user (optional)
  local key="$1" model="$2" user="${3:-}" body
  body="$(jq -nc --arg m "$model" --arg u "$user" \
    '{model:$m, user:$u, messages:[{role:"user",content:"hi"}]}')"
  http_code "$LAB/v1/chat/completions" -X POST \
    -H "Authorization: Bearer $key" -H "Content-Type: $JSON" -d "$body"
}

# send one message, print the response object
invoke_chat() { # $1 = uri, $2 = bearer, $3 = model, $4 = content
  local body
  body="$(jq -nc --arg m "$3" --arg c "$4" \
    '{model:$m, messages:[{role:"user",content:$c}]}')"
  lab_curl -sS -X POST "$1" -H "Authorization: Bearer $2" -H "Content-Type: $JSON" -d "$body"
}

# = token() in the original: access token from Keycloak (password grant)
get_lab_token() { # $1 = username (password = username)
  lab_curl -sS -X POST "$IDP_URL/realms/$IDP_REALM/protocol/openid-connect/token" \
    -d grant_type=password -d client_id=lab-app \
    --data-urlencode "username=$1" --data-urlencode "password=$1" | jq -r '.access_token'
}

# = $KC in the original: kcadm inside the idp container (stdin works: ... | kc update ... -f -)
kc() { docker compose exec -T idp /opt/keycloak/bin/kcadm.sh "$@"; }

# = W in the original: send a billing webhook to subscription-service (Step 8)
send_billing() { # $1 = json event
  lab_curl -sS -X POST "$BILLING_URL/webhook/billing" \
    -H "Content-Type: $JSON" -H "x-webhook-secret: $WEBHOOK_SECRET" -d "$1"
}

# print model_list entries for every OPENAI_COMPATIBLE_<n>_* in .env (compat-1, compat-2, ...)
# -> paste into litellm/config.yaml
get_compat_yaml() {
  local n m
  for n in $(env | sed -nE 's/^OPENAI_COMPATIBLE_([0-9]+)_BASE_URL=.*/\1/p' | sort -n); do
    eval "m=\${OPENAI_COMPATIBLE_${n}_MODEL}"
    printf '  - model_name: compat-%s\n' "$n"
    printf '    litellm_params:\n'
    printf '      model: openai/%s\n' "$m"
    printf '      api_base: os.environ/OPENAI_COMPATIBLE_%s_BASE_URL\n' "$n"
    printf '      api_key: os.environ/OPENAI_COMPATIBLE_%s_API_KEY\n' "$n"
    printf '    model_info:\n'
    printf '      access_groups: [tier-basic, tier-pro]\n'
  done
}

# what the tests are pointed at (handy after changing LAB_HOST)
lab_env() {
  printf 'LAB_ROOT     %s\n' "$LAB_ROOT"
  printf 'LAB_HOST     %s\n' "$LAB_HOST"
  printf 'LAB          %s\n' "$LAB"
  printf 'IDP_URL      %s/realms/%s\n' "$IDP_URL" "$IDP_REALM"
  printf 'BILLING_URL  %s\n' "$BILLING_URL"
  printf 'API_URL      %s\n' "$API_URL"
  printf 'LLM_URL      %s\n' "$LLM_URL"
  printf 'CURL_OPTS    %s\n' "${LAB_CURL_OPTS:-(none)}"
}
